### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pierreablin** [bgoujaud/PEPit#36]
Hi and thanks for the great package !

The link to the demo in the readme seems broken: https://github.com/bgoujaud/PEPit/blob/master/ressources/educational/PEPit_demo.ipynb

**Comment by AdrienTaylor** [comment]
Hello Pierre!

Thanks a lot for the feedback; it is indeed not the good link in the current version on pip; we'll update it shortly!
(I guess you found the working link, but in the case you didn't it is here: https://github.com/bgoujaud/PEPit/blob/master/ressources/demo/PEPit_demo.ipynb).

Thanks again!
